### PR TITLE
Fix grammar errors.

### PR DESCRIPTION
**Pull request by pedrominicz**
Title says everything.

### CODE REVIEW

**Comment by jonniedie** [comment]
Well, if we’re going to revert the grammar errors, we might as well got rid of the “An Amazing Project” part too.

**Comment by pedrominicz** [comment]
I don't know man... you so enthusiastically accepted the last pull request.

**Comment by jonniedie** [comment]
That's why I'm so sad to see it go.

**Comment by jonniedie** [comment]
A round of t-shirts on me.

**Comment by pedrominicz** [comment]
They changed things for Hacktoberfest. Now the repo has to have "hacktoberfest" somewhere on the topic or the PR has to labeled "hacktoberfest-accepted." This may also help the last guy.

**Pull request merged**
